<?php
namespace controllers;

 use Ubiquity\attributes\items\router\Route;
 use Ubiquity\utils\http\USession;

 /**
 * Controller TodoController
 **/
class TodoController extends ControllerBase{

    const CACHE_KEY = 'datas/lists/';
    const EMPTY_LIST_ID='not saved';
    const LIST_SESSION_KEY='list';
    const ACTIVE_LIST_SESSION_KEY='active-list';

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->menu();
    }

    #[Route('_default',name: 'home')]
    public function index(){
        if(USession::exists(self::LIST_SESSION_KEY)){
            $list = USession::get(self::LIST_SESSION_KEY);
            return $this->displayList($list);
        }

    }

}
